### PR TITLE
allow split openings

### PR DESCRIPTION
**Pull request by yubo56**
Allow v, V, f, F to open a buffer in a vertical or horizontal split

### CODE REVIEW

**Comment by yubo56** [comment]
@jlanzarotta I don't use many of the fancier use cases that bufexplorer apparently supports, e.g. winmgr or tabs, so if you could help me fix this up that would be great!

Also, I prefer using s/S to split but it seems like it's already been used :(

**Comment by jlanzarotta** [comment]
Hello,

Let me check into this.  I am sure that you should be able to change the mappings to those keys...

**Comment by yubo56** [comment]
Haha, it's not just a matter of what keys to use, e.g. we could just bump sorting order to something esoteric, mostly wanna make sure my code covers all use cases since there are a lot that I don't understand :weary:

**Comment by jlanzarotta** [comment]
Thanks, got your code.  I will take a look at it.

**Comment by jlanzarotta** [comment]
I have merged your code in locally and I am currently testing it.  So far so good.

**Comment by yubo56** [comment]
Cool! Sorry just saw this. Has been working fine for me too fwiw

**Comment by yubo56** [comment]
@jlanzarotta Any updates? Would be nice to point pathogen back to your repo instead of my fork :)

**Comment by jlanzarotta** [comment]
So far so good.  I will hopefully commit the final version sometime today.

**Comment by jlanzarotta** [comment]
Okay, I believe I have the latest released finally...

**Comment by yubo56** [comment]
yay I see it thanks!

**Pull request closed without merging**
